name: 'Package.json version bump enforcer'
author: '@thepassle'
description: 'Enforces a version bump in the package.json'
inputs:
  skipLabel:
    description: 'Name of the label used to skip enforcing a changelog change'
    required: true
    default: 'Skip-Changelog'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'check-square'
  color: 'orange'